#!/usr/bin/env python3
"""Build the uwu theme for KDE Plasma 6 (kde/plasma/).

* colour schemes: UwuNight, UwuDay (apps, panels, launcher, everything)
* Plasma style "uwu": candy-shaped panel, popups, tooltips, taskbar buttons,
  launcher list items, search field, buttons and tabs. Every colour comes
  from the colour scheme (Plasma's ColorScheme-* classes), so one style works
  for both night and day.
* window decorations (Aurorae): uwu-night, uwu-day, with pastel candy buttons
* launcher icon

The splash screen, global themes and wallpaper come from
tools/plasma_extras.py.

Plasma frames are 9-slice SVGs: each frame is drawn as separate pieces
(topleft, top, …, center) whose geometry is computed here, so corners stay
round however big the panel or popup gets. Borders tile, the centre stretches.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "kde" / "plasma"

# ─────────────────────────────── palettes ───────────────────────────────
NIGHT = dict(
    name="UwuNight", title="uwu night",
    window="#241530", window_alt="#2c1a39", text="#ffeaf6", inactive="#c79dbb",
    view="#1b0f22", view_alt="#22142b", button="#3a2244", button_alt="#462a52",
    header="#2e1a3a", header_inactive="#241530", tooltip="#2c1838", complementary="#140a1a",
    select="#ff8fc8", select_text="#2a0c22", focus="#ff8fc8", hover="#c7a2ff",
    link="#9fd8ff", visited="#c7a2ff", negative="#ff6b8f", neutral="#ffd27a", positive="#8ff5cf",
    active_text="#ff8fc8",
)
DAY = dict(
    name="UwuDay", title="uwu day",
    window="#fff2f8", window_alt="#ffe8f2", text="#57264c", inactive="#9a5f8a",
    view="#ffffff", view_alt="#fff6fa", button="#ffe4f1", button_alt="#ffd6ea",
    header="#ffe1ef", header_inactive="#fff2f8", tooltip="#fff7fb", complementary="#2a1630",
    select="#e8438f", select_text="#ffffff", focus="#e8438f", hover="#a77bff",
    link="#2f8fd8", visited="#8a4fe0", negative="#e0365f", neutral="#c98a00", positive="#1fae7a",
    active_text="#e8438f",
)


def rgb(h):
    h = h.lstrip("#")
    return ",".join(str(int(h[i:i + 2], 16)) for i in (0, 2, 4))


# ─────────────────────────────── colour schemes ───────────────────────────────
def colour_scheme(p):
    night = p is NIGHT
    comp = dict(NIGHT, window=NIGHT["complementary"], view="#120914", view_alt="#1a0e1f",
                button="#2c1838", button_alt="#36203f") if not night else dict(p, window=p["complementary"])

    def group(name, bg, alt, q=p):
        return "\n".join([
            f"[Colors:{name}]",
            f"BackgroundAlternate={rgb(alt)}",
            f"BackgroundNormal={rgb(bg)}",
            f"DecorationFocus={rgb(q['focus'])}",
            f"DecorationHover={rgb(q['hover'])}",
            f"ForegroundActive={rgb(q['active_text'])}",
            f"ForegroundInactive={rgb(q['inactive'])}",
            f"ForegroundLink={rgb(q['link'])}",
            f"ForegroundNegative={rgb(q['negative'])}",
            f"ForegroundNeutral={rgb(q['neutral'])}",
            f"ForegroundNormal={rgb(q['text'])}",
            f"ForegroundPositive={rgb(q['positive'])}",
            f"ForegroundVisited={rgb(q['visited'])}",
            "",
        ])

    sel = dict(p, text=p["select_text"], inactive=p["select_text"], active_text=p["select_text"])
    return "\n".join([
        "# ♡ uwu colour scheme. Generated by tools/plasma_theme.py",
        "[ColorEffects:Disabled]", "Color=56,56,56", "ColorAmount=0", "ColorEffect=0",
        "ContrastAmount=0.65", "ContrastEffect=1", "IntensityAmount=0.1", "IntensityEffect=2", "",
        "[ColorEffects:Inactive]", "ChangeSelectionColor=true", "Color=112,111,110", "ColorAmount=0.025",
        "ColorEffect=2", "ContrastAmount=0.1", "ContrastEffect=2", "Enable=false",
        "IntensityAmount=0", "IntensityEffect=0", "",
        group("Button", p["button"], p["button_alt"]),
        group("Complementary", comp["window"], comp["window_alt"], NIGHT if not night else p),
        group("Header", p["header"], p["window_alt"]),
        group("Header][Inactive", p["header_inactive"], p["window_alt"]),
        group("Selection", p["select"], p["select"], sel),
        group("Tooltip", p["tooltip"], p["window_alt"]),
        group("View", p["view"], p["view_alt"]),
        group("Window", p["window"], p["window_alt"]),
        "[General]",
        f"ColorScheme={p['name']}",
        f"Name={p['title']}",
        "shadeSortColumn=true", "",
        "[KDE]", "contrast=4", "",
        "[WM]",
        f"activeBackground={rgb(p['header'])}",
        f"activeBlend={rgb(p['select'])}",
        f"activeForeground={rgb(p['text'])}",
        f"inactiveBackground={rgb(p['header_inactive'])}",
        f"inactiveBlend={rgb(p['inactive'])}",
        f"inactiveForeground={rgb(p['inactive'])}",
        "",
    ])


# ─────────────────────────────── SVG frame helpers ───────────────────────────────
STYLE_NIGHT = {
    "Text": NIGHT["text"], "Background": NIGHT["window"], "Highlight": NIGHT["select"],
    "ViewBackground": NIGHT["view"], "ButtonBackground": NIGHT["button"],
    "ButtonHover": NIGHT["hover"], "ButtonFocus": NIGHT["focus"], "NeutralText": NIGHT["neutral"],
    "PositiveText": NIGHT["positive"], "NegativeText": NIGHT["negative"], "HighlightedText": NIGHT["select_text"],
}


def svg_doc(w, h, body):
    style = "\n".join(f"      .ColorScheme-{k} {{ color:{v}; }}" for k, v in STYLE_NIGHT.items())
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        "<!-- ♡ uwu Plasma style. Generated by tools/plasma_theme.py; colours follow the colour scheme. -->\n"
        f'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" '
        f'width="{w}" height="{h}" viewBox="0 0 {w} {h}">\n'
        '  <defs>\n    <style type="text/css" id="current-color-scheme">\n'
        f"{style}\n    </style>\n  </defs>\n{body}\n</svg>\n"
    )


def f(v):
    return f"{v:.3f}".rstrip("0").rstrip(".")


def element_id(prefix, name):
    return f"{prefix}-{name}" if prefix else name


def invisible(x, y, w, h):
    return f'<rect x="{f(x)}" y="{f(y)}" width="{f(w)}" height="{f(h)}" fill="#000" opacity="0"/>'


def corner_band(kind, x0, y0, cw, ch, r, t0, t1=None):
    """Path for the band between offsets t0..t1 inside a rounded corner.

    The corner box is cw x ch with its outer corner at (x0, y0) for "tl" and
    mirrored for "tr" / "bl" / "br"; the outer edge is rounded with radius r.
    t1 = None gives the whole filled corner. Pure fills, so Qt reports
    exact bounds (strokes would pad them).
    """
    fx = kind[1] == "r"   # mirror horizontally
    fy = kind[0] == "b"   # mirror vertically

    def pt(lx, ly):
        return (x0 - lx if fx else x0 + lx), (y0 - ly if fy else y0 + ly)

    def curve(t, forward=True):
        """Points along the outer edge at offset t: from the far end of the top edge to the far end of the side."""
        rr = max(r - t, 0)
        a = pt(cw, t)
        b = pt(max(r, t), t)
        c = pt(t, max(r, t))
        d = pt(t, ch)
        return a, b, c, d, rr

    sweep = 0 if fx == fy else 1
    a0, b0, c0, d0, r0 = curve(t0)
    P = lambda q: f"{f(q[0])},{f(q[1])}"
    arc0 = f"A{f(r0)},{f(r0)} 0 0 {sweep} {P(c0)}" if r0 > 0 else f"L{P(c0)}"
    if t1 is None:
        # the whole corner: rounded outer edge, closed off at the inner corner of the box
        return f"M{P(a0)} L{P(b0)} {arc0} L{P(d0)} L{P(pt(cw, ch))} Z"
    a1, b1, c1, d1, r1 = curve(t1)
    arc1 = f"A{f(r1)},{f(r1)} 0 0 {1 - sweep} {P(b1)}" if r1 > 0 else f"L{P(b1)}"
    return f"M{P(a0)} L{P(b0)} {arc0} L{P(d0)} L{P(d1)} L{P(c1)} {arc1} L{P(a1)} Z"


def frame(prefix, ox, oy, *, c, L=16, r=None, fill=None, border=None, bw=1.5, gloss=0.0,
          dash=None, round_corners="tltrblbr", border_sides="tlbr"):
    """One 9-slice frame. fill/border = (ColorScheme class or #hex, opacity).

    `round_corners` lists the rounded corners as two-letter codes ("tltr" =
    top-left + top-right), `border_sides` which edges (t/l/b/r) get the
    border line, `dash` = (on, off) makes the edge borders dashed (on + off
    should equal L, since Plasma tiles the edges).
    """
    r = c if r is None else r
    assert r <= c, "corner radius must fit inside the corner piece"
    X0, X1, X2, X3 = ox, ox + c, ox + c + L, ox + 2 * c + L
    Y0, Y1, Y2, Y3 = oy, oy + c, oy + c + L, oy + 2 * c + L
    corners = {round_corners[i:i + 2] for i in range(0, len(round_corners), 2)}

    def paint(what, d):
        if what is None or not d:
            return ""
        col, op = what
        if col.startswith("#"):
            return f'<path d="{d}" fill="{col}" opacity="{op}"/>'
        return f'<path class="ColorScheme-{col}" d="{d}" fill="currentColor" opacity="{op}"/>'

    rect = lambda x, y, w, h: f"M{f(x)},{f(y)} H{f(x + w)} V{f(y + h)} H{f(x)} Z" if w > 0 and h > 0 else ""
    out = []

    def piece(name, box, fill_d, border_d="", gloss_d=""):
        x, y, w, h = box
        parts = [invisible(x, y, w, h), paint(fill, fill_d), paint(border, border_d)]
        if gloss and gloss_d:
            parts.append(f'<path d="{gloss_d}" fill="#fff" opacity="{gloss}"/>')
        out.append(f'<g id="{element_id(prefix, name)}">' + "".join(parts) + "</g>")

    sides = set(border_sides)
    origin = {"tl": (X0, Y0), "tr": (X3, Y0), "bl": (X0, Y3), "br": (X3, Y3)}
    boxes = {"tl": (X0, Y0), "tr": (X2, Y0), "bl": (X0, Y2), "br": (X2, Y2)}
    names = {"tl": "topleft", "tr": "topright", "bl": "bottomleft", "br": "bottomright"}
    for k in ("tl", "tr", "bl", "br"):
        bx, by = boxes[k]
        if k in corners and r > 0:
            ox_, oy_ = origin[k]
            fd = corner_band(k, ox_, oy_, c, c, r, 0, None)
            bd = corner_band(k, ox_, oy_, c, c, r, 0, bw) if border else ""
            gd = corner_band(k, ox_, oy_, c, c, r, bw + 0.4, bw + 1.4) if k[0] == "t" else ""
        else:
            fd = rect(bx, by, c, c)
            vert = "t" if k[0] == "t" else "b"
            horiz = "l" if k[1] == "l" else "r"
            bits = []
            if vert in sides:
                bits.append(rect(bx, by if vert == "t" else by + c - bw, c, bw))
            if horiz in sides:
                bits.append(rect(bx if horiz == "l" else bx + c - bw, by, bw, c))
            bd = " ".join(b for b in bits if b) if border else ""
            gd = rect(bx, by + bw + 0.4, c, 1) if vert == "t" and "t" in sides else ""
        piece(names[k], (bx, by, c, c), fd, bd, gd)

    def edge_border(x, y, w, h, horizontal):
        if not border:
            return ""
        if not dash:
            return rect(x, y, w, h)
        on = dash[0]
        return rect(x, y, on, h) if horizontal else rect(x, y, w, on)

    piece("top", (X1, Y0, L, c), rect(X1, Y0, L, c), edge_border(X1, Y0, L, bw, True) if "t" in sides else "",
          rect(X1, Y0 + bw + 0.4, L, 1) if "t" in sides else "")
    piece("bottom", (X1, Y2, L, c), rect(X1, Y2, L, c), edge_border(X1, Y3 - bw, L, bw, True) if "b" in sides else "")
    piece("left", (X0, Y1, c, L), rect(X0, Y1, c, L), edge_border(X0, Y1, bw, L, False) if "l" in sides else "")
    piece("right", (X2, Y1, c, L), rect(X2, Y1, c, L), edge_border(X3 - bw, Y1, bw, L, False) if "r" in sides else "")
    piece("center", (X1, Y1, L, L), rect(X1, Y1, L, L))
    return "\n".join(out), (X3 - X0, Y3 - Y0)


def hints(prefix, ox, oy, top, bottom, left, right, kind="margin"):
    """Plasma reads content margins (and insets) from the size of these invisible elements."""
    p = f"{prefix}-" if prefix else ""
    return "\n".join([
        f'<rect id="{p}hint-top-{kind}" x="{ox}" y="{oy}" width="4" height="{top}" fill="#000" opacity="0"/>',
        f'<rect id="{p}hint-bottom-{kind}" x="{ox + 6}" y="{oy}" width="4" height="{bottom}" fill="#000" opacity="0"/>',
        f'<rect id="{p}hint-left-{kind}" x="{ox}" y="{oy + 30}" width="{left}" height="4" fill="#000" opacity="0"/>',
        f'<rect id="{p}hint-right-{kind}" x="{ox}" y="{oy + 36}" width="{right}" height="4" fill="#000" opacity="0"/>',
    ])


SHADOW = "#2a0a24"


def shadow_frame(ox, oy, s=16, L=16, strength=0.42, prefix="shadow"):
    """Soft plum shadow pieces, strongest at the inner edge, a bit heavier below."""
    X0, X1, X2, X3 = ox, ox + s, ox + s + L, ox + 2 * s + L
    Y0, Y1, Y2, Y3 = oy, oy + s, oy + s + L, oy + 2 * s + L
    out, defs = [], []
    n = 0

    def grad_radial(cx, cy, a):
        nonlocal n
        n += 1
        gid = f"{prefix}g{n}x{ox}"
        defs.append(f'<radialGradient id="{gid}" gradientUnits="userSpaceOnUse" cx="{cx}" cy="{cy}" r="{s}">'
                    f'<stop offset="0" stop-color="{SHADOW}" stop-opacity="{a:.3f}"/>'
                    f'<stop offset=".45" stop-color="{SHADOW}" stop-opacity="{a * .45:.3f}"/>'
                    f'<stop offset="1" stop-color="{SHADOW}" stop-opacity="0"/></radialGradient>')
        return gid

    def grad_linear(x1, y1, x2, y2, a):
        nonlocal n
        n += 1
        gid = f"{prefix}g{n}x{ox}"
        defs.append(f'<linearGradient id="{gid}" gradientUnits="userSpaceOnUse" x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}">'
                    f'<stop offset="0" stop-color="{SHADOW}" stop-opacity="{a:.3f}"/>'
                    f'<stop offset=".45" stop-color="{SHADOW}" stop-opacity="{a * .45:.3f}"/>'
                    f'<stop offset="1" stop-color="{SHADOW}" stop-opacity="0"/></linearGradient>')
        return gid

    top_a, side_a, bot_a = strength * .7, strength, strength * 1.25
    pieces = [
        ("topleft", (X0, Y0, s, s), grad_radial(X1, Y1, (top_a + side_a) / 2)),
        ("topright", (X2, Y0, s, s), grad_radial(X2, Y1, (top_a + side_a) / 2)),
        ("bottomleft", (X0, Y2, s, s), grad_radial(X1, Y2, (bot_a + side_a) / 2)),
        ("bottomright", (X2, Y2, s, s), grad_radial(X2, Y2, (bot_a + side_a) / 2)),
        ("top", (X1, Y0, L, s), grad_linear(0, Y1, 0, Y0, top_a)),
        ("bottom", (X1, Y2, L, s), grad_linear(0, Y2, 0, Y3, bot_a)),
        ("left", (X0, Y1, s, L), grad_linear(X1, 0, X0, 0, side_a)),
        ("right", (X2, Y1, s, L), grad_linear(X2, 0, X3, 0, side_a)),
    ]
    for name, (x, y, w, hh), gid in pieces:
        out.append(f'<rect id="{prefix}-{name}" x="{x}" y="{y}" width="{w}" height="{hh}" fill="url(#{gid})"/>')
    out.append(f'<rect id="{prefix}-center" x="{X1}" y="{Y1}" width="{L}" height="{L}" fill="#000" opacity="0"/>')
    return "<defs>" + "".join(defs) + "</defs>\n" + "\n".join(out), (X3 - X0, Y3 - Y0)


def shadow_hints(ox, oy, margin=10, inset=10):
    out = []
    for kind, v in (("margin", margin), ("inset", inset)):
        out.append(hints("shadow", ox + (0 if kind == "margin" else 14), oy, v, v, v, v, kind))
    return "\n".join(out)


# ─────────────────────────────── Plasma style files ───────────────────────────────
def framed_surface(r, c, fill_op, border_op, margins, shadow=True, gloss=0.07, inset=0):
    """panel / popup / tooltip / desktop-widget background."""
    body, (w, h) = frame("", 0, 0, c=c, r=r, fill=("Background", fill_op), border=("Highlight", border_op), bw=1.5, gloss=gloss)
    parts = [body, hints("", w + 8, 0, *margins)]
    parts.append(hints("", w + 8, 50, inset, inset, inset, inset, "inset"))
    if shadow:
        sh, (sw, shh) = shadow_frame(0, h + 10)
        parts += [sh, shadow_hints(sw + 8, h + 10)]
        return svg_doc(max(w, sw) + 60, h + shh + 20, "\n".join(parts))
    return svg_doc(w + 60, h + 20, "\n".join(parts))


def states_file(states, *, c, r, L=16, bw=1.5, margins=None, extra=""):
    """A file with several prefixed frames stacked vertically (tasks, viewitem, buttons…)."""
    parts, y, width = [], 0, 0
    for prefix, kw in states:
        body, (w, h) = frame(prefix, 0, y, c=c, r=r, L=L, bw=kw.pop("bw", bw), **kw)
        parts.append(body)
        if margins is not None:
            parts.append(hints(prefix, w + 8, y, *margins))
        y += h + 6
        width = max(width, w)
    return svg_doc(width + 60, y, "\n".join(parts) + extra)


def busywidget():
    # a ring of hearts and dots that Plasma spins
    import math
    items = []
    for i in range(8):
        a = i * math.pi / 4
        x, y = 32 + math.cos(a) * 22, 32 + math.sin(a) * 22
        if i % 2 == 0:
            items.append(f'<path class="ColorScheme-Highlight" fill="currentColor" opacity="{0.4 + 0.6 * (i / 8):.2f}" '
                         f'transform="translate({f(x)} {f(y)}) rotate({f(math.degrees(a) + 90)}) scale(1.1)" '
                         'd="M0 3C-1.5 0-6-1-6 2.5c0 2.6 3 4.6 6 7 3-2.4 6-4.4 6-7C6-1 1.5 0 0 3z" />')
        else:
            items.append(f'<circle class="ColorScheme-ButtonHover" fill="currentColor" cx="{f(x)}" cy="{f(y)}" r="3" opacity="{0.4 + 0.6 * (i / 8):.2f}"/>')
    return svg_doc(64, 64, '<g id="busywidget">' + invisible(0, 0, 64, 64) + "".join(items) + "</g>")


def plasma_style():
    d = OUT / "desktoptheme" / "uwu"
    (d / "widgets").mkdir(parents=True, exist_ok=True)
    (d / "dialogs").mkdir(parents=True, exist_ok=True)
    (d / "metadata.json").write_text("""{
    "KPlugin": {
        "Authors": [{ "Name": "uwu" }],
        "Category": "",
        "Description": "Candy pastel panels, popups and taskbar with sakura vibes ♡ (colours follow your colour scheme: try uwu night / uwu day)",
        "EnabledByDefault": true,
        "Id": "uwu",
        "License": "MIT",
        "Name": "uwu",
        "Version": "1.0",
        "Website": "https://github.com/folkedevvy/opencode-web-uwu"
    },
    "X-Plasma-API": "5.0"
}
""")
    files = {
        # the panel (task bar): a rounded candy bar
        "widgets/panel-background.svg": framed_surface(14, 16, 0.92, 0.45, (6, 6, 6, 6)),
        # popups: launcher, system tray, calendar…
        "dialogs/background.svg": framed_surface(16, 18, 0.96, 0.5, (8, 8, 8, 8)),
        "widgets/tooltip.svg": framed_surface(12, 12, 0.97, 0.55, (8, 8, 10, 10)),
        # desktop widgets
        "widgets/background.svg": framed_surface(18, 18, 0.88, 0.4, (10, 10, 10, 10)),
        # task bar buttons
        "widgets/tasks.svg": states_file([
            ("normal", dict(fill=("Text", 0.05), border=("Text", 0.08))),
            ("hover", dict(fill=("ButtonHover", 0.22), border=("ButtonHover", 0.6), gloss=0.08)),
            ("focus", dict(fill=("ButtonFocus", 0.3), border=("ButtonFocus", 0.85), gloss=0.1, bw=2)),
            ("attention", dict(fill=("NeutralText", 0.32), border=("NeutralText", 0.85), bw=2)),
            ("minimized", dict(fill=("Text", 0.02), border=("Text", 0.3), dash=(4, 4))),
            ("progress", dict(fill=("PositiveText", 0.3), border=("PositiveText", 0.6))),
        ], c=10, r=10, L=8, margins=(3, 3, 4, 4)),
        # hover / selection in lists (launcher, system tray, menus)
        "widgets/viewitem.svg": states_file([
            ("normal", dict(fill=("Text", 0.0), border=None)),
            ("hover", dict(fill=("Highlight", 0.18), border=("Highlight", 0.45))),
            ("selected", dict(fill=("Highlight", 0.3), border=("Highlight", 0.7))),
            ("selected+hover", dict(fill=("Highlight", 0.38), border=("Highlight", 0.85))),
        ], c=10, r=10, margins=(5, 5, 5, 5)),
        # buttons
        "widgets/button.svg": states_file([
            ("normal", dict(fill=("ButtonBackground", 0.95), border=("Text", 0.16), gloss=0.07)),
            ("hover", dict(fill=("ButtonBackground", 0.95), border=("ButtonHover", 0.9), gloss=0.07)),
            ("pressed", dict(fill=("ButtonFocus", 0.35), border=("ButtonFocus", 0.9))),
            ("focus", dict(fill=("ButtonBackground", 0.95), border=("ButtonFocus", 1), bw=2)),
            ("toolbutton-hover", dict(fill=("ButtonHover", 0.2), border=("ButtonHover", 0.6))),
            ("toolbutton-focus", dict(fill=("ButtonFocus", 0.12), border=("ButtonFocus", 0.9), bw=2)),
            ("toolbutton-pressed", dict(fill=("ButtonFocus", 0.32), border=("ButtonFocus", 0.8))),
        ], c=10, r=10, margins=(5, 5, 8, 8)),
        # search field
        "widgets/lineedit.svg": states_file([
            ("base", dict(fill=("ViewBackground", 0.9), border=("Text", 0.18))),
            ("hover", dict(fill=None, border=("ButtonHover", 0.85))),
            ("focus", dict(fill=None, border=("ButtonFocus", 1), bw=2)),
        ], c=12, r=12, margins=None, extra="\n" + hints("base", 120, 0, 6, 6, 12, 12)
            + "\n" + hints("hover", 120, 60, 0, 0, 0, 0) + "\n" + hints("focus", 120, 120, 0, 0, 0, 0)
            + '\n<rect id="hint-focus-over-base" x="200" y="0" width="2" height="2" fill="#000" opacity="0"/>'),
        # tabs (launcher's Applications / Places, etc.)
        "widgets/tabbar.svg": states_file([
            (f"{side}-active-tab", dict(fill=("Highlight", 0.25), border=("Highlight", 0.7)))
            for side in ("north", "south", "east", "west")
        ], c=10, r=10, margins=(4, 4, 8, 8)),
        "widgets/busywidget.svg": busywidget(),
    }
    # header and footer strips inside popups (the launcher's search bar and its tab bar)
    head, (w, h) = frame("header", 0, 0, c=16, r=15, L=8, fill=("Highlight", 0.09), border=("Highlight", 0.55),
                         bw=1.5, round_corners="tltr", border_sides="b", dash=(4, 4))
    foot, _ = frame("footer", w + 10, 0, c=16, r=15, L=8, fill=("Highlight", 0.06), border=("Highlight", 0.55),
                    bw=1.5, round_corners="blbr", border_sides="t", dash=(4, 4))
    files["widgets/plasmoidheading.svg"] = svg_doc(2 * w + 80, h + 50, "\n".join([head, foot, hints("", 2 * w + 20, 0, 6, 6, 8, 8)]))

    for name, text in files.items():
        (d / name).write_text(text)
    return d


# ─────────────────────────────── window decoration (Aurorae) ───────────────────────────────
P_LEFT, P_RIGHT, P_TOP, P_BOTTOM = 14, 14, 8, 18  # shadow padding
SIDE = 6                                          # side / bottom frame (Normal border size allows up to 6)
TITLE_EDGE_TOP, TITLE_H, TITLE_EDGE_BOTTOM = 4, 26, 4
TOP = TITLE_EDGE_TOP + TITLE_H + TITLE_EDGE_BOTTOM


def aurorae(p, name):
    d = OUT / "aurorae" / name
    d.mkdir(parents=True, exist_ok=True)
    night = p is NIGHT
    bar, bar_in = p["header"], p["header_inactive"]
    edge, edge_in = p["select"], p["inactive"]

    def decoration(prefix, ox, oy, fill_col, line_col, line_op, shadow_a):
        """Rounded window frame with a soft shadow in the padding around it.

        Every piece is built from exact geometry (no clipping or blur), because
        Plasma sizes each piece from its bounding box.
        """
        L = 16
        lw, rw, th, bh = P_LEFT + SIDE, P_RIGHT + SIDE, P_TOP + TOP, P_BOTTOM + SIDE
        X0, X1, X2, X3 = ox, ox + lw, ox + lw + L, ox + lw + L + rw
        Y0, Y1, Y2, Y3 = oy, oy + th, oy + th + L, oy + th + L + bh
        wx0, wy0, wx1, wy1 = X0 + P_LEFT, Y0 + P_TOP, X3 - P_RIGHT, Y3 - P_BOTTOM  # the window itself
        r = SIDE
        dy = 3                               # shadow falls a little downwards
        layers = [(k, shadow_a * 0.11 * (1 - k / 12) ** 1.6) for k in range(1, 12)]
        P = lambda d, col, op: f'<path d="{d}" fill="{col}" opacity="{op:.3f}"/>'
        S = lambda d, op: f'<path d="{d}" fill="{line_col}" opacity="{op}"/>'
        G = lambda d: f'<path d="{d}" fill="#fff" opacity="{0.10 if night else 0.6}"/>'
        bw = 1.5
        rect = lambda x0, y0, x1, y1: f"M{f(x0)},{f(y0)} H{f(x1)} V{f(y1)} H{f(x0)} Z"

        def shadow(shape_for_k):
            return "".join(P(shape_for_k(k), SHADOW, a) for k, a in layers)

        pieces = {}
        # ── corners ──
        pieces["topleft"] = (
            (X0, Y0, lw, th),
            shadow(lambda k: f"M{f(X1)},{f(wy0 + dy - k)} A{f(r + k)},{f(r + k)} 0 0 0 {f(wx0 - k)},{f(wy0 + dy + r)} V{f(Y1)} H{f(X1)} Z")
            + P(f"M{f(X1)},{f(wy0)} A{r},{r} 0 0 0 {f(wx0)},{f(wy0 + r)} V{f(Y1)} H{f(X1)} Z", fill_col, 1)
            + S(corner_band("tl", wx0, wy0, X1 - wx0, Y1 - wy0, r, 0, bw), line_op)
            + G(corner_band("tl", wx0, wy0, X1 - wx0, r, r, 2, 3)))
        pieces["topright"] = (
            (X2, Y0, rw, th),
            shadow(lambda k: f"M{f(X2)},{f(wy0 + dy - k)} A{f(r + k)},{f(r + k)} 0 0 1 {f(wx1 + k)},{f(wy0 + dy + r)} V{f(Y1)} H{f(X2)} Z")
            + P(f"M{f(X2)},{f(wy0)} A{r},{r} 0 0 1 {f(wx1)},{f(wy0 + r)} V{f(Y1)} H{f(X2)} Z", fill_col, 1)
            + S(corner_band("tr", wx1, wy0, wx1 - X2, Y1 - wy0, r, 0, bw), line_op)
            + G(corner_band("tr", wx1, wy0, wx1 - X2, r, r, 2, 3)))
        pieces["bottomleft"] = (
            (X0, Y2, lw, bh),
            shadow(lambda k: f"M{f(wx0 - k)},{f(Y2)} V{f(wy1 - r + dy)} A{f(r + k)},{f(r + k)} 0 0 0 {f(X1)},{f(wy1 + dy + k)} V{f(Y2)} Z")
            + P(f"M{f(wx0)},{f(Y2)} V{f(wy1 - r)} A{r},{r} 0 0 0 {f(X1)},{f(wy1)} V{f(Y2)} Z", fill_col, 1)
            + S(corner_band("bl", wx0, wy1, X1 - wx0, wy1 - Y2, r, 0, bw), line_op))
        pieces["bottomright"] = (
            (X2, Y2, rw, bh),
            shadow(lambda k: f"M{f(wx1 + k)},{f(Y2)} V{f(wy1 - r + dy)} A{f(r + k)},{f(r + k)} 0 0 1 {f(X2)},{f(wy1 + dy + k)} V{f(Y2)} Z")
            + P(f"M{f(wx1)},{f(Y2)} V{f(wy1 - r)} A{r},{r} 0 0 1 {f(X2)},{f(wy1)} V{f(Y2)} Z", fill_col, 1)
            + S(corner_band("br", wx1, wy1, wx1 - X2, wy1 - Y2, r, 0, bw), line_op))
        # ── edges ──
        pieces["top"] = (
            (X1, Y0, L, th),
            shadow(lambda k: rect(X1, wy0 + dy - k, X2, Y1))
            + P(rect(X1, wy0, X2, Y1), fill_col, 1) + S(rect(X1, wy0, X2, wy0 + bw), line_op)
            + G(rect(X1, wy0 + 2, X2, wy0 + 3)))
        pieces["bottom"] = (
            (X1, Y2, L, bh),
            shadow(lambda k: rect(X1, Y2, X2, wy1 + dy + k))
            + P(rect(X1, Y2, X2, wy1), fill_col, 1) + S(rect(X1, wy1 - bw, X2, wy1), line_op))
        pieces["left"] = (
            (X0, Y1, lw, L),
            shadow(lambda k: rect(wx0 - k, Y1, X1, Y2))
            + P(rect(wx0, Y1, X1, Y2), fill_col, 1) + S(rect(wx0, Y1, wx0 + bw, Y2), line_op))
        pieces["right"] = (
            (X2, Y1, rw, L),
            shadow(lambda k: rect(X2, Y1, wx1 + k, Y2))
            + P(rect(X2, Y1, wx1, Y2), fill_col, 1) + S(rect(wx1 - bw, Y1, wx1, Y2), line_op))
        pieces["center"] = ((X1, Y1, L, L), P(rect(X1, Y1, X2, Y2), fill_col, 1))

        out = []
        for nm, ((x, y, w, hh), art) in pieces.items():
            out.append(f'<g id="{prefix}-{nm}">{invisible(x, y, w, hh)}{art}</g>')
        return "\n".join(out), (X3 - X0, Y3 - Y0)

    def maximized(prefix, ox, oy, fill_col, line_col):
        L = 16
        pieces = []
        rect = lambda x, y, w, h, c, o=1: f'<rect x="{x}" y="{y}" width="{w}" height="{h}" fill="{c}" opacity="{o}"/>'
        boxes = {"center": (ox, oy, L, TOP)}
        for nm, (x, y, w, h) in boxes.items():
            pieces.append(f'<g id="{prefix}-{nm}">{rect(x, y, w, h, fill_col)}{rect(x, y + h - 1.5, w, 1.5, line_col, .5)}</g>')
        return "\n".join(pieces), (L, TOP)

    a, (w, h) = decoration("decoration", 0, 0, bar, edge, 0.75, 0.55 if night else 0.32)
    b, _ = decoration("decoration-inactive", w + 20, 0, bar_in, edge_in, 0.45, 0.32 if night else 0.18)
    c, _ = maximized("decoration-maximized", 2 * w + 40, 0, bar, edge)
    e, _ = maximized("decoration-maximized-inactive", 2 * w + 80, 0, bar_in, edge_in)
    (d / "decoration.svg").write_text(svg_doc(2 * w + 120, h + 10, "\n".join([a, b, c, e])))

    # candy buttons: butter (minimise), mint (maximise), hot pink (close); glyphs show on hover
    colours = ({"minimize": "#ffe59a", "maximize": "#8ff5cf", "restore": "#8ff5cf", "close": "#ff6fb5",
                "alldesktops": "#c7a2ff", "keepabove": "#c7a2ff", "keepbelow": "#c7a2ff", "shade": "#9fd8ff", "help": "#9fd8ff"}
               if night else  # deeper candy so the buttons stand out on the light title bar
               {"minimize": "#ffc93c", "maximize": "#34cf98", "restore": "#34cf98", "close": "#ff4f9a",
                "alldesktops": "#a77bff", "keepabove": "#a77bff", "keepbelow": "#a77bff", "shade": "#4aa8e8", "help": "#4aa8e8"})
    ink = "#4a1340"
    glyphs = {
        "minimize": '<path d="M8.5 12h7" stroke="{c}" stroke-width="2.2" stroke-linecap="round"/>',
        "maximize": '<path d="M12 8.2v7.6M8.2 12h7.6" stroke="{c}" stroke-width="2.2" stroke-linecap="round"/>',
        "restore": '<path d="M9 12h6" stroke="{c}" stroke-width="2.2" stroke-linecap="round"/><circle cx="12" cy="12" r="3.6" fill="none" stroke="{c}" stroke-width="1.6"/>',
        "close": '<path fill="{c}" transform="translate(12 10.2) scale(.62)" d="M0 3C-1.5 0-6-1-6 2.5c0 2.6 3 4.6 6 7 3-2.4 6-4.4 6-7C6-1 1.5 0 0 3z"/>',
        "alldesktops": '<circle cx="12" cy="12" r="2.6" fill="{c}"/>',
        "keepabove": '<path d="M8.5 13.5l3.5-3.5 3.5 3.5" fill="none" stroke="{c}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>',
        "keepbelow": '<path d="M8.5 10.5l3.5 3.5 3.5-3.5" fill="none" stroke="{c}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>',
        "shade": '<path d="M8.5 10h7M8.5 14h7" stroke="{c}" stroke-width="2" stroke-linecap="round"/>',
        "help": '<path d="M10 10a2 2 0 1 1 2.6 1.9c-.5.2-.6.6-.6 1.1M12 15.6v.1" fill="none" stroke="{c}" stroke-width="2" stroke-linecap="round"/>',
    }
    for btn, col in colours.items():
        def state(prefix, ox, fill, glyph, ring, scale=1.0, op=1.0):
            g = glyphs[btn].format(c=ink) if glyph else ""
            ringd = f'<circle cx="12" cy="12" r="10.2" fill="none" stroke="{col}" stroke-width="1.5" opacity=".55"/>' if ring else ""
            return (f'<g id="{prefix}-center" transform="translate({ox} 0)">{invisible(0, 0, 24, 24)}'
                    f'<g transform="translate(12 12) scale({scale}) translate(-12 -12)" opacity="{op}">{ringd}'
                    f'<circle cx="12" cy="12" r="7.5" fill="{fill}"/>'
                    f'<circle cx="10" cy="9.6" r="2.2" fill="#fff" opacity=".45"/>{g}</g></g>')
        muted = p["inactive"]
        parts = [
            state("active", 0, col, False, False),
            state("hover", 30, col, True, True, 1.08),
            state("pressed", 60, col, True, False, 0.92),
            state("deactivated", 90, muted, False, False, 1, 0.4),
            state("inactive", 120, muted, False, False, 1, 0.55),
            state("hover-inactive", 150, col, True, True, 1.08),
            state("pressed-inactive", 180, col, True, False, 0.92),
            state("deactivated-inactive", 210, muted, False, False, 1, 0.3),
        ]
        (d / f"{btn}.svg").write_text(svg_doc(240, 24, "\n".join(parts)))

    text = rgb(p["text"])
    (d / f"{name}rc").write_text(f"""# ♡ uwu window decoration. Generated by tools/plasma_theme.py
[General]
ActiveTextColor={text}
InactiveTextColor={rgb(p['inactive'])}
UseTextShadow=false
TitleAlignment=Center
TitleVerticalAlignment=Center
Animation=160
Shadow=true
DecorationPosition=0

[Layout]
BorderLeft={SIDE}
BorderRight={SIDE}
BorderBottom={SIDE}
BorderTop=0
TitleEdgeTop={TITLE_EDGE_TOP}
TitleEdgeBottom={TITLE_EDGE_BOTTOM}
TitleEdgeLeft=8
TitleEdgeRight=8
TitleEdgeTopMaximized={TITLE_EDGE_TOP}
TitleEdgeBottomMaximized={TITLE_EDGE_BOTTOM}
TitleEdgeLeftMaximized=6
TitleEdgeRightMaximized=6
TitleBorderLeft=8
TitleBorderRight=8
TitleHeight={TITLE_H}
ButtonWidth=24
ButtonHeight=24
ButtonSpacing=4
ButtonMarginTop=1
ButtonMarginTopMaximized=1
ExplicitButtonSpacer=10
PaddingLeft={P_LEFT}
PaddingRight={P_RIGHT}
PaddingTop={P_TOP}
PaddingBottom={P_BOTTOM}
""")
    (d / "metadata.desktop").write_text(f"""[Desktop Entry]
Name={p['title']}
Comment=Candy-pastel title bars with butter, mint and heart buttons ♡
X-KDE-PluginInfo-Author=uwu
X-KDE-PluginInfo-Name={name}
X-KDE-PluginInfo-Version=1.0
X-KDE-PluginInfo-License=MIT
X-KDE-PluginInfo-Category=
X-KDE-PluginInfo-Website=https://github.com/folkedevvy/opencode-web-uwu
""")
    return d


# ─────────────────────────────── launcher icon ───────────────────────────────
def launcher_icon():
    from kawaii_assets import LOGO
    d = OUT / "icons"
    d.mkdir(parents=True, exist_ok=True)
    (d / "uwu-launcher.svg").write_text(LOGO)


def main():
    cs = OUT / "color-schemes"
    cs.mkdir(parents=True, exist_ok=True)
    for p in (NIGHT, DAY):
        (cs / f"{p['name']}.colors").write_text(colour_scheme(p))
    plasma_style()
    aurorae(NIGHT, "uwu-night")
    aurorae(DAY, "uwu-day")
    launcher_icon()
    print("wrote", OUT)


if __name__ == "__main__":
    main()
