#!/usr/bin/env python3
"""Generate the uwu-code colour themes (dark + light) for VS Code.

Built from tools/palette.py so it matches the opencode web and TUI themes.

    python3 tools/vscode_theme.py
"""
import json
from pathlib import Path

from palette import PALETTE

OUT = Path(__file__).resolve().parent.parent / "vscode" / "uwu-code" / "themes"

# extra shades only VS Code needs: (dark, light)
EXTRA = {
    "bgDeep":     ("#170d1d", "#ffe1ef"),
    "bgRaised":   ("#462b56", "#ffd3e9"),
    "selection":  ("#ff8fc84d", "#ff5fae38"),
    "selectionDim": ("#c7a2ff2e", "#8a4fe024"),
    "lineHi":     ("#ff8fc812", "#ff5fae10"),
    "find":       ("#ffe59a55", "#ffd96680"),
    "findDim":    ("#ffe59a26", "#ffd96640"),
    "wordHi":     ("#c7a2ff26", "#8a4fe01f"),
    "hover":      ("#ff8fc81a", "#ff5fae14"),
    "scroll":     ("#ff8fc833", "#e8438f2e"),
    "scrollHover": ("#ff8fc855", "#e8438f4d"),
    "shadow":     ("#0a000f80", "#e8438f26"),
    "param":      ("#ffb79a", "#e0703f"),
    "teal":       ("#7fe3e0", "#1a8f8c"),
    "white":      ("#fff6fb", "#3e1436"),
    "black":      ("#2a1733", "#fff0f7"),
}

C = {**PALETTE, **EXTRA}


def col(name, mode, alpha=None):
    value = C[name][0 if mode == "dark" else 1]
    return value + alpha if alpha else value


def workbench(m):
    c = lambda n, a=None: col(n, m, a)  # noqa: E731
    return {
        # base
        "focusBorder": c("pink", "99"),
        "foreground": c("text"),
        "descriptionForeground": c("textMuted"),
        "disabledForeground": c("lineNo"),
        "errorForeground": c("cherry"),
        "icon.foreground": c("textMuted"),
        "selection.background": c("selection"),
        "widget.shadow": c("shadow"),
        "widget.border": c("border"),
        "sash.hoverBorder": c("pink"),
        "textLink.foreground": c("pink"),
        "textLink.activeForeground": c("hotPink"),
        "textBlockQuote.background": c("bgPanel"),
        "textBlockQuote.border": c("pink"),
        "textCodeBlock.background": c("bgPanel"),
        "textPreformat.foreground": c("mint"),
        "textSeparator.foreground": c("border"),
        "progressBar.background": c("pink"),
        "badge.background": c("pink"),
        "badge.foreground": c("ink"),
        # buttons & inputs
        "button.background": c("pink"),
        "button.foreground": c("ink"),
        "button.hoverBackground": c("hotPink"),
        "button.secondaryBackground": c("bgElement"),
        "button.secondaryForeground": c("text"),
        "button.secondaryHoverBackground": c("bgRaised"),
        "button.border": "#00000000",
        "checkbox.background": c("bgElement"),
        "checkbox.border": c("border"),
        "checkbox.foreground": c("pink"),
        "input.background": c("bgPanel"),
        "input.border": c("border"),
        "input.foreground": c("text"),
        "input.placeholderForeground": c("lineNo"),
        "inputOption.activeBackground": c("pink", "33"),
        "inputOption.activeBorder": c("pink"),
        "inputOption.activeForeground": c("text"),
        "inputValidation.errorBackground": c("delBg"),
        "inputValidation.errorBorder": c("cherry"),
        "inputValidation.warningBackground": c("bgElement"),
        "inputValidation.warningBorder": c("butter"),
        "inputValidation.infoBackground": c("bgElement"),
        "inputValidation.infoBorder": c("sky"),
        "dropdown.background": c("bgPanel"),
        "dropdown.border": c("border"),
        "dropdown.foreground": c("text"),
        "dropdown.listBackground": c("bgPanel"),
        "keybindingLabel.background": c("bgElement"),
        "keybindingLabel.foreground": c("text"),
        "keybindingLabel.border": c("border"),
        "keybindingLabel.bottomBorder": c("border"),
        # lists & trees
        "list.activeSelectionBackground": c("pink", "38"),
        "list.activeSelectionForeground": c("text"),
        "list.activeSelectionIconForeground": c("pink"),
        "list.inactiveSelectionBackground": c("pink", "1f"),
        "list.inactiveSelectionForeground": c("text"),
        "list.hoverBackground": c("hover"),
        "list.hoverForeground": c("text"),
        "list.focusOutline": c("pink", "80"),
        "list.focusBackground": c("pink", "26"),
        "list.highlightForeground": c("pink"),
        "list.focusHighlightForeground": c("hotPink"),
        "list.errorForeground": c("cherry"),
        "list.warningForeground": c("butter"),
        "list.dropBackground": c("pink", "26"),
        "tree.indentGuidesStroke": c("border"),
        "tree.inactiveIndentGuidesStroke": c("borderSubtle"),
        # activity bar
        "activityBar.background": c("bgDeep"),
        "activityBar.foreground": c("pink"),
        "activityBar.inactiveForeground": c("lineNo"),
        "activityBar.border": c("borderSubtle"),
        "activityBar.activeBorder": c("pink"),
        "activityBar.activeBackground": c("pink", "14"),
        "activityBarBadge.background": c("pink"),
        "activityBarBadge.foreground": c("ink"),
        # side bar
        "sideBar.background": c("bgPanel"),
        "sideBar.foreground": c("text"),
        "sideBar.border": c("borderSubtle"),
        "sideBarTitle.foreground": c("pink"),
        "sideBarSectionHeader.background": c("bgPanel"),
        "sideBarSectionHeader.foreground": c("lavender"),
        "sideBarSectionHeader.border": c("borderSubtle"),
        # tabs & editor groups
        "editorGroup.border": c("borderSubtle"),
        "editorGroup.dropBackground": c("pink", "1f"),
        "editorGroupHeader.tabsBackground": c("bgDeep"),
        "editorGroupHeader.tabsBorder": c("borderSubtle"),
        "editorGroupHeader.noTabsBackground": c("bgDeep"),
        "tab.activeBackground": c("bg"),
        "tab.activeForeground": c("text"),
        "tab.activeBorderTop": c("pink"),
        "tab.activeBorder": c("bg"),
        "tab.inactiveBackground": c("bgDeep"),
        "tab.inactiveForeground": c("textMuted"),
        "tab.hoverBackground": c("bgPanel"),
        "tab.hoverForeground": c("text"),
        "tab.border": c("borderSubtle"),
        "tab.unfocusedActiveBorderTop": c("lavender", "80"),
        "tab.unfocusedActiveForeground": c("textMuted"),
        "tab.unfocusedInactiveForeground": c("lineNo"),
        "tab.activeModifiedBorder": c("butter"),
        "tab.inactiveModifiedBorder": c("butter", "80"),
        "breadcrumb.foreground": c("textMuted"),
        "breadcrumb.focusForeground": c("text"),
        "breadcrumb.activeSelectionForeground": c("pink"),
        "breadcrumb.background": c("bg"),
        "breadcrumbPicker.background": c("bgPanel"),
        # editor
        "editor.background": c("bg"),
        "editor.foreground": c("text"),
        "editorLineNumber.foreground": c("lineNo"),
        "editorLineNumber.activeForeground": c("pink"),
        "editorCursor.foreground": c("pink"),
        "editorCursor.background": c("ink"),
        "editor.selectionBackground": c("selection"),
        "editor.inactiveSelectionBackground": c("selectionDim"),
        "editor.selectionHighlightBackground": c("wordHi"),
        "editor.wordHighlightBackground": c("wordHi"),
        "editor.wordHighlightStrongBackground": c("pink", "2e"),
        "editor.findMatchBackground": c("find"),
        "editor.findMatchBorder": c("butter"),
        "editor.findMatchHighlightBackground": c("findDim"),
        "editor.findRangeHighlightBackground": c("lineHi"),
        "editor.hoverHighlightBackground": c("wordHi"),
        "editor.lineHighlightBackground": c("lineHi"),
        "editor.lineHighlightBorder": "#00000000",
        "editor.rangeHighlightBackground": c("lineHi"),
        "editorLink.activeForeground": c("sky"),
        "editorWhitespace.foreground": c("borderSubtle"),
        "editorIndentGuide.background1": c("borderSubtle"),
        "editorIndentGuide.activeBackground1": c("pink", "80"),
        "editorRuler.foreground": c("borderSubtle"),
        "editorCodeLens.foreground": c("lineNo"),
        "editorBracketMatch.background": c("pink", "26"),
        "editorBracketMatch.border": c("pink", "99"),
        "editorBracketHighlight.foreground1": c("pink"),
        "editorBracketHighlight.foreground2": c("lavender"),
        "editorBracketHighlight.foreground3": c("mint"),
        "editorBracketHighlight.foreground4": c("sky"),
        "editorBracketHighlight.foreground5": c("butter"),
        "editorBracketHighlight.foreground6": c("peach"),
        "editorBracketHighlight.unexpectedBracket.foreground": c("cherry"),
        "editorError.foreground": c("cherry"),
        "editorWarning.foreground": c("butter"),
        "editorInfo.foreground": c("sky"),
        "editorHint.foreground": c("mint"),
        "editorUnnecessaryCode.opacity": "#000000a0",
        "editorGutter.background": c("bg"),
        "editorGutter.addedBackground": c("mint", "cc"),
        "editorGutter.modifiedBackground": c("lavender", "cc"),
        "editorGutter.deletedBackground": c("cherry", "cc"),
        "editorOverviewRuler.border": "#00000000",
        "editorOverviewRuler.addedForeground": c("mint", "99"),
        "editorOverviewRuler.modifiedForeground": c("lavender", "99"),
        "editorOverviewRuler.deletedForeground": c("cherry", "99"),
        "editorOverviewRuler.errorForeground": c("cherry"),
        "editorOverviewRuler.warningForeground": c("butter"),
        "editorOverviewRuler.findMatchForeground": c("butter", "99"),
        "editorInlayHint.background": c("bgElement", "b3"),
        "editorInlayHint.foreground": c("textMuted"),
        "editorGhostText.foreground": c("lineNo"),
        "editorStickyScroll.background": c("bg"),
        "editorStickyScrollHover.background": c("bgPanel"),
        # widgets
        "editorWidget.background": c("bgPanel"),
        "editorWidget.foreground": c("text"),
        "editorWidget.border": c("border"),
        "editorSuggestWidget.background": c("bgPanel"),
        "editorSuggestWidget.border": c("border"),
        "editorSuggestWidget.foreground": c("text"),
        "editorSuggestWidget.selectedBackground": c("pink", "33"),
        "editorSuggestWidget.selectedForeground": c("text"),
        "editorSuggestWidget.highlightForeground": c("pink"),
        "editorSuggestWidget.focusHighlightForeground": c("hotPink"),
        "editorHoverWidget.background": c("bgPanel"),
        "editorHoverWidget.border": c("border"),
        "peekView.border": c("pink"),
        "peekViewEditor.background": c("bgPanel"),
        "peekViewEditor.matchHighlightBackground": c("find"),
        "peekViewResult.background": c("bgDeep"),
        "peekViewResult.selectionBackground": c("pink", "33"),
        "peekViewResult.matchHighlightBackground": c("find"),
        "peekViewTitle.background": c("bgElement"),
        "peekViewTitleLabel.foreground": c("pink"),
        "peekViewTitleDescription.foreground": c("textMuted"),
        # diff
        "diffEditor.insertedTextBackground": c("mint", "26"),
        "diffEditor.removedTextBackground": c("cherry", "26"),
        "diffEditor.insertedLineBackground": c("addBg", "b3"),
        "diffEditor.removedLineBackground": c("delBg", "b3"),
        "diffEditor.diagonalFill": c("borderSubtle"),
        # scrollbars & minimap
        "scrollbar.shadow": c("shadow"),
        "scrollbarSlider.background": c("scroll"),
        "scrollbarSlider.hoverBackground": c("scrollHover"),
        "scrollbarSlider.activeBackground": c("pink", "80"),
        "minimap.selectionHighlight": c("pink", "80"),
        "minimap.findMatchHighlight": c("butter", "80"),
        "minimapGutter.addedBackground": c("mint"),
        "minimapGutter.modifiedBackground": c("lavender"),
        "minimapGutter.deletedBackground": c("cherry"),
        # panel & terminal
        "panel.background": c("bgPanel"),
        "panel.border": c("borderSubtle"),
        "panelTitle.activeBorder": c("pink"),
        "panelTitle.activeForeground": c("text"),
        "panelTitle.inactiveForeground": c("textMuted"),
        "panelInput.border": c("border"),
        "terminal.background": c("bgPanel"),
        "terminal.foreground": c("text"),
        "terminal.selectionBackground": c("selection"),
        "terminalCursor.foreground": c("pink"),
        "terminal.ansiBlack": c("black"),
        "terminal.ansiRed": c("cherry"),
        "terminal.ansiGreen": c("mint"),
        "terminal.ansiYellow": c("butter"),
        "terminal.ansiBlue": c("sky"),
        "terminal.ansiMagenta": c("pink"),
        "terminal.ansiCyan": c("teal"),
        "terminal.ansiWhite": c("text"),
        "terminal.ansiBrightBlack": c("lineNo"),
        "terminal.ansiBrightRed": c("delHi"),
        "terminal.ansiBrightGreen": c("addHi"),
        "terminal.ansiBrightYellow": c("butter"),
        "terminal.ansiBrightBlue": c("sky"),
        "terminal.ansiBrightMagenta": c("hotPink"),
        "terminal.ansiBrightCyan": c("teal"),
        "terminal.ansiBrightWhite": c("white"),
        # status bar & title bar
        "statusBar.background": c("bgDeep"),
        "statusBar.foreground": c("textMuted"),
        "statusBar.border": c("borderSubtle"),
        "statusBar.debuggingBackground": c("lavender"),
        "statusBar.debuggingForeground": c("ink"),
        "statusBar.noFolderBackground": c("bgDeep"),
        "statusBar.noFolderForeground": c("textMuted"),
        "statusBarItem.hoverBackground": c("pink", "26"),
        "statusBarItem.activeBackground": c("pink", "40"),
        "statusBarItem.remoteBackground": c("pink"),
        "statusBarItem.remoteForeground": c("ink"),
        "statusBarItem.prominentBackground": c("pink", "33"),
        "statusBarItem.errorBackground": c("cherry"),
        "statusBarItem.errorForeground": c("ink"),
        "titleBar.activeBackground": c("bgDeep"),
        "titleBar.activeForeground": c("text"),
        "titleBar.inactiveBackground": c("bgDeep"),
        "titleBar.inactiveForeground": c("textMuted"),
        "titleBar.border": c("borderSubtle"),
        "commandCenter.background": c("bgPanel"),
        "commandCenter.foreground": c("text"),
        "commandCenter.border": c("border"),
        "commandCenter.activeBackground": c("bgElement"),
        "menubar.selectionBackground": c("hover"),
        "menu.background": c("bgPanel"),
        "menu.foreground": c("text"),
        "menu.selectionBackground": c("pink", "38"),
        "menu.selectionForeground": c("text"),
        "menu.separatorBackground": c("border"),
        "menu.border": c("border"),
        # quick input, notifications
        "quickInput.background": c("bgPanel"),
        "quickInput.foreground": c("text"),
        "quickInputList.focusBackground": c("pink", "38"),
        "quickInputList.focusForeground": c("text"),
        "quickInputTitle.background": c("bgElement"),
        "pickerGroup.foreground": c("lavender"),
        "pickerGroup.border": c("border"),
        "notifications.background": c("bgPanel"),
        "notifications.foreground": c("text"),
        "notifications.border": c("border"),
        "notificationCenterHeader.background": c("bgElement"),
        "notificationLink.foreground": c("pink"),
        "notificationsErrorIcon.foreground": c("cherry"),
        "notificationsWarningIcon.foreground": c("butter"),
        "notificationsInfoIcon.foreground": c("sky"),
        "toolbar.hoverBackground": c("hover"),
        # git & misc
        "gitDecoration.addedResourceForeground": c("mint"),
        "gitDecoration.modifiedResourceForeground": c("lavender"),
        "gitDecoration.deletedResourceForeground": c("cherry"),
        "gitDecoration.untrackedResourceForeground": c("mint"),
        "gitDecoration.ignoredResourceForeground": c("lineNo"),
        "gitDecoration.conflictingResourceForeground": c("peach"),
        "gitDecoration.renamedResourceForeground": c("sky"),
        "settings.headerForeground": c("pink"),
        "settings.modifiedItemIndicator": c("pink"),
        "extensionButton.prominentBackground": c("pink"),
        "extensionButton.prominentForeground": c("ink"),
        "extensionButton.prominentHoverBackground": c("hotPink"),
        "welcomePage.tileBackground": c("bgPanel"),
        "walkThrough.embeddedEditorBackground": c("bgPanel"),
        "debugToolBar.background": c("bgPanel"),
        "charts.red": c("cherry"),
        "charts.blue": c("sky"),
        "charts.yellow": c("butter"),
        "charts.orange": c("peach"),
        "charts.green": c("mint"),
        "charts.purple": c("lavender"),
        "charts.foreground": c("text"),
        "charts.lines": c("border"),
    }


def tokens(m):
    c = lambda n: col(n, m)  # noqa: E731

    def rule(name, scope, fg=None, style=None):
        settings = {}
        if fg:
            settings["foreground"] = c(fg)
        if style is not None:
            settings["fontStyle"] = style
        return {"name": name, "scope": scope, "settings": settings}

    return [
        rule("Comments", ["comment", "punctuation.definition.comment"], "plum", "italic"),
        rule("Keywords", ["keyword", "storage.type", "storage.modifier", "keyword.control"], "pink"),
        rule("Operators", ["keyword.operator", "punctuation.separator.key-value"], "operator", ""),
        rule("Strings", ["string", "string.quoted", "string.template"], "mint"),
        rule("String escapes", ["constant.character.escape", "string.regexp"], "butter"),
        rule("Template expressions", ["punctuation.definition.template-expression", "punctuation.section.embedded"], "pink"),
        rule("Numbers", ["constant.numeric"], "sky"),
        rule("Constants", ["constant.language", "constant.other", "variable.other.constant", "support.constant"], "peach"),
        rule("Functions", ["entity.name.function", "support.function", "meta.function-call.generic", "variable.function"], "lavender"),
        rule("Types", ["entity.name.type", "entity.name.class", "support.type", "support.class", "entity.other.inherited-class", "storage.type.class"], "butter"),
        rule("Variables", ["variable", "variable.other.readwrite", "meta.definition.variable"], "text"),
        rule("Parameters", ["variable.parameter"], "param", "italic"),
        rule("Properties", ["variable.other.property", "variable.other.object.property", "support.variable.property", "meta.object-literal.key"], "blush"),
        rule("this/self", ["variable.language"], "pink", "italic"),
        rule("Punctuation", ["punctuation", "meta.brace", "punctuation.terminator"], "punct"),
        rule("Tags", ["entity.name.tag"], "pink"),
        rule("Attributes", ["entity.other.attribute-name"], "lavender", "italic"),
        rule("CSS properties", ["support.type.property-name"], "sky"),
        rule("CSS values", ["support.constant.property-value", "constant.other.color"], "peach"),
        rule("Markdown headings", ["markup.heading", "entity.name.section"], "pink", "bold"),
        rule("Markdown bold", ["markup.bold"], "hotPink", "bold"),
        rule("Markdown italic", ["markup.italic"], "lavender", "italic"),
        rule("Markdown code", ["markup.inline.raw", "markup.fenced_code"], "mint"),
        rule("Markdown links", ["markup.underline.link", "string.other.link"], "sky"),
        rule("Markdown quotes", ["markup.quote"], "blush", "italic"),
        rule("Markdown lists", ["punctuation.definition.list.begin.markdown", "beginning.punctuation.definition.list"], "pink"),
        rule("Diff inserted", ["markup.inserted"], "mint"),
        rule("Diff deleted", ["markup.deleted"], "cherry"),
        rule("Diff changed", ["markup.changed"], "lavender"),
        rule("Invalid", ["invalid", "invalid.illegal"], "cherry", "underline"),
        rule("Decorators", ["meta.decorator", "entity.name.function.decorator", "punctuation.decorator"], "peach", "italic"),
        rule("Namespaces", ["entity.name.namespace", "entity.name.module"], "butter"),
        rule("JSON keys", ["support.type.property-name.json"], "lavender"),
    ]


def semantic(m):
    c = lambda n: col(n, m)  # noqa: E731
    return {
        "function": c("lavender"),
        "method": c("lavender"),
        "class": c("butter"),
        "interface": c("butter"),
        "type": c("butter"),
        "enum": c("butter"),
        "namespace": c("butter"),
        "typeParameter": {"foreground": c("butter"), "italic": True},
        "enumMember": c("peach"),
        "property": c("blush"),
        "parameter": {"foreground": c("param"), "italic": True},
        "variable": c("text"),
        "variable.readonly": c("peach"),
        "variable.defaultLibrary": c("peach"),
        "keyword": c("pink"),
        "decorator": {"foreground": c("peach"), "italic": True},
        "macro": c("pink"),
    }


def build(mode):
    return {
        "$schema": "vscode://schemas/color-theme",
        "name": f"uwu {'strawberry-milk night' if mode == 'dark' else 'sakura cream day'}",
        "type": mode,
        "semanticHighlighting": True,
        "colors": workbench(mode),
        "tokenColors": tokens(mode),
        "semanticTokenColors": semantic(mode),
    }


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for mode in ("dark", "light"):
        path = OUT / f"uwu-{mode}-color-theme.json"
        path.write_text(json.dumps(build(mode), indent=2, ensure_ascii=False) + "\n")
        print("wrote", path)


if __name__ == "__main__":
    main()
